version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - npm install --production
  pre_build:
    commands:
      - echo Configure AWS CLI...
      - aws configure set aws_access_key_id $AWS_CREDENTIALS_ACCESS_KEY
      - aws configure set aws_secret_access_key $AWS_CREDENTIALS_SECRET_KEY
      - aws configure set default.region $AWS_DEFAULT_REGION
      - aws configure set default.max_payload_size 104857600
      - echo Verify and update handler
      - ./scripts/lambda-handler.sh
  build:
    commands:
      - npm run build
  post_build:
    commands:
      - echo Remove scripts from code
      - rm -rf scripts src test .git
      - echo Creating package of code
      - zip -r package.zip .
      - echo Updating function code in AWS Lambda...
      - FUNCTION_NAME=$(aws ssm get-parameter --name "/lambda/MoviesFunctionArn" --query "Parameter.Value" --output text | awk -F'[:/]' '{print $NF}')
      - aws lambda update-function-code --function-name $FUNCTION_NAME --zip-file fileb://package.zip